import {WEATHER_CONDITIONS} from './weather-widget.types'

// const RAINY_RANGE = {min: 200, max: 522}
// const SNOWY_RANGE = {min: 600, max: 610}
// const CLOUDY_RANGE = {min: 611, max: 612}
// const SNOWY_RANGE = {min: 621, max: 623}
// const CLOUDY_RANGE = {min: 700, max: 751}
// const SUNNY_RANGE = {min: 800, max: 801}
// const CLOUDY_RANGE = {min: 802, max: 804}
// const RAINY_RANGE = {min: 805, max: 900}

// TODO TROVARE UN MODO MIGLIORE
export const MAP_WEATHER_CODE_TO_TYPE = {
    200: WEATHER_CONDITIONS.RAINY,
    201: WEATHER_CONDITIONS.RAINY,
    202: WEATHER_CONDITIONS.RAINY,
    230: WEATHER_CONDITIONS.RAINY,
    231: WEATHER_CONDITIONS.RAINY,
    232: WEATHER_CONDITIONS.RAINY,
    233: WEATHER_CONDITIONS.RAINY,
    300: WEATHER_CONDITIONS.RAINY,
    301: WEATHER_CONDITIONS.RAINY,
    302: WEATHER_CONDITIONS.RAINY,
    500: WEATHER_CONDITIONS.RAINY,
    501: WEATHER_CONDITIONS.RAINY,
    502: WEATHER_CONDITIONS.RAINY,
    511: WEATHER_CONDITIONS.RAINY,
    520: WEATHER_CONDITIONS.RAINY,
    521: WEATHER_CONDITIONS.RAINY,
    522: WEATHER_CONDITIONS.RAINY,
    600: WEATHER_CONDITIONS.SNOWY,
    601: WEATHER_CONDITIONS.SNOWY,
    602: WEATHER_CONDITIONS.SNOWY,
    610: WEATHER_CONDITIONS.SNOWY,
    611: WEATHER_CONDITIONS.CLOUDY,
    612: WEATHER_CONDITIONS.CLOUDY,
    621: WEATHER_CONDITIONS.SNOWY,
    622: WEATHER_CONDITIONS.SNOWY,
    623: WEATHER_CONDITIONS.SNOWY,
    700: WEATHER_CONDITIONS.CLOUDY,
    711: WEATHER_CONDITIONS.CLOUDY,
    721: WEATHER_CONDITIONS.CLOUDY,
    731: WEATHER_CONDITIONS.CLOUDY,
    741: WEATHER_CONDITIONS.CLOUDY,
    751: WEATHER_CONDITIONS.CLOUDY,
    800: WEATHER_CONDITIONS.SUNNY,
    801: WEATHER_CONDITIONS.SUNNY,
    802: WEATHER_CONDITIONS.CLOUDY,
    803: WEATHER_CONDITIONS.CLOUDY,
    804: WEATHER_CONDITIONS.CLOUDY,
    900: WEATHER_CONDITIONS.RAINY,
}